springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"
  security:
    enabled: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: true
  h2:
    console:
      enabled: true